# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from app/src directory to the working directory
COPY src/app/package*.json ./

# Install dependencies
RUN npm install

# Copy the public directory to the working directory in the container

# Copy the rest of your application code from the current directory to the working directory
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
